import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TernSecureProvider, UserButton } from "@tern-secure/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TernSecureProvider 
          requiresVerification={true}  //default is true
          customDomain="http://localhost:4000"
          isTernSecureDev={true}  //use popup mode. if redirect on localhost it cannot 
        > 
        <UserButton />
        {children}
        </TernSecureProvider>
      </body>
    </html>
  );
}
